language: swift
osx_image: xcode11
sudo: required

env:
  global:
    - PROJECT="Swiftline.xcodeproj"
    - JOB="XCODE"
    - DEST="platform=macOS,arch=x86_64"

jobs:
  include:
    - stage: test
      name: "Tests"
      script:
        - set -o pipefail
        - xcodebuild test -project "$PROJECT" -scheme "SwiftlineTests" -destination "$DEST" | xcpretty -c
